### ISSUE TITLE
Crash on world load.

### ISSUE THREAD

**Issue by TheSnowyChickens** [Shadows-of-Fire/Placebo#10]
Hi,
any world that I create, crashes on world load. Only without Placebo (+ mods), the world load.

I don't get a crash report, only the classic hs_err errors.
[hs_err_pid2436.log](https://github.com/Shadows-of-Fire/Placebo/files/3588251/hs_err_pid2436.log)

I use: 
Forge: 28.0.100
Placebo: 2.2.0
FWB: 2.1.0
FF: 2.2.0
WST: 3.1.0
MC: 1.14.4

Mod list:
![grafik](https://user-images.githubusercontent.com/29357962/64496977-b38ac480-d2aa-11e9-8495-fb2200cc3706.png)

**Comment by Shadows-of-Fire** [comment]
None of my mods ever access NativeImage whatsoever, nor is there any problem that I can tell from running all of my mods together in an environment with forge 100.
It's possible that this issue stems from either video drivers or a jvm issue (the hs_err_pid is reporting multiple installed jdk's), so try removing all java installs and installing j8 from https://adoptopenjdk.net/

**Comment by TheSnowyChickens** [comment]
Okay Sir, thx for this info and this Java beta/pre-build page. 👍

**Comment by TheSnowyChickens** [comment]
Hmm,
still the same error. ;/

I will try tomorrow more and I wait for new mod updates from the other mods, maybe they are also "destroying" something.

[hs_err_pid14872.log](https://github.com/Shadows-of-Fire/Placebo/files/3588330/hs_err_pid14872.log)

**Comment by Shadows-of-Fire** [comment]
Well the crash is from native image code, video drivers are also a possible cause.  See if there are updates available

**Comment by TheSnowyChickens** [comment]
![grafik](https://user-images.githubusercontent.com/29357962/64498048-d8833580-d2b2-11e9-84f8-01c0c2424650.png)
It is the newest version.
(Grafiktreiber -> graphic driver)

**Comment by TheSnowyChickens** [comment]
Okay, I found the problematic mod: it was god damn JEI, but only this time.
At the time, where I posted this issue, it was another mod. (feels like random mods causing this xd)

But still ty for helping me. 👍
