### ISSUE TITLE
1.16.4 below 1.16.36?

### ISSUE THREAD

**Issue by PrimalRook** [Shadows-of-Fire/Placebo#18]
![What](https://user-images.githubusercontent.com/77701009/105097611-3039cf80-5aa9-11eb-9c4c-94b3ce6f1c1d.JPG)

Could someone explain this error to me? My forged version seems to be higher than what is asked for, but it doesn't work.

**Comment by Shadows-of-Fire** [comment]
4 < 36
Update to latest
