### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by drkanbs** [Shadows-of-Fire/Placebo#22]
two possible mods that caused it, Placebo or Nomorerecipeconflict.  So I'm submitting to you as well. 

[crash-2021-05-27_11.35.31-client.txt](https://github.com/Shadows-of-Fire/Placebo/files/6555583/crash-2021-05-27_11.35.31-client.txt)

**Comment by Shadows-of-Fire** [comment]
mc 1.12 is not supported
