### ISSUE TITLE
placebo 4.60 keeps crashing my minecraft before it can load

### ISSUE THREAD

**Issue by RegalTocaro** [Shadows-of-Fire/Placebo#24]
does anyone else find this problem? I can't even get out of the Minecraft launcher after clicking play. it straight up crashes. is there any way to fix this? the mods I'm using require placebo 4.60 or higher so I can't download another version as much as I'd like to.

**Comment by WithoutAName25** [comment]
I had the same issue, here are my log files:
[debug.log](https://github.com/Shadows-of-Fire/Placebo/files/7231205/debug.log)
[latest.log](https://github.com/Shadows-of-Fire/Placebo/files/7231206/latest.log)

**Comment by Shadows-of-Fire** [comment]
well the original report has no data and your logs are mixin errors from other mods, nothing from placebo (placebo doesnt even have mixins).
