### ISSUE TITLE
Failed to Load Correctly 1.18.1 Placebo-1.18.1-6.0.4

### ISSUE THREAD

**Issue by Quantumniko** [Shadows-of-Fire/Placebo#35]
Fails to load
[crash-2022-01-24_16.10.31-fml.txt](https://github.com/Shadows-of-Fire/Placebo/files/7922806/crash-2022-01-24_16.10.31-fml.txt)

[latest.log](https://github.com/Shadows-of-Fire/Placebo/files/7922824/latest.log)

Mod List

> Just Enough Items (JEI) (by mezz)
Goblin Traders (by MrCrayfish)
Toast Control (by Shadows_of_Fire)
Legendary Tooltips (by Grend_G)
BlockUI (by H3lay)
Gauges and Switches (by wilechaote)
Flat Bedrock (by Sunekaer)
Carry On (by Tschipp)
I Know What I'm Doing (IKWID) (by HeckinChloe)
Simple Voice Chat (by henkelmax)
Connected Glass (by SuperMartijn642)
Create Chunkloading (by embeddedt)
AppleSkin (by squeek502)
Advanced Netherite (by AutovwLive)
Simply Light (by Flanks255)
My Server Is Compatible (by Focamacho)
Lootr (by Noobanidus)
Sapience (by the_infamous_1)
Signpost (by Gollorum)
Equipment Compare (by Grend_G)
MineColonies (by H3lay)
Citadel (by alex_khaan)
GeckoLib (by ThanosGecko)
Occultism (by kli_kli)
FastFurnace (by Shadows_of_Fire)
Guard Villagers (by almightytallestred)
Better Compatibility Checker (by Gaz_)
Macaw's Trapdoors (by sketch_macaw)
Amplified Nether (by Starmute)
Create (by simibubi)
Advancement Plaques (by Grend_G)
mutil (by mickelus)
Connectivity (by someaddon)
Terralith 2.0 ~ Overworld Evolved (by Starmute)
Patchouli (by Vazkii)
Corail Woodcutter (by Corail_31)
Structurize (by H3lay)
Inventory Essentials (by BlayTheNinth)
Hexerei (by JoeFoxe)
Notes (by Chaosyr)
Farsight[Forge/Fabric] (by someaddon)
Login Protection[Forge/Fabric] (by someaddon)
Macaw's Windows (by sketch_macaw)
Malum (by sammysemicolon)
Creeper Overhaul (by rubyr1derr)
AntiGhost (by Giselbaer)
Farming for Blockheads (by BlayTheNinth)
Repurposed Structures (Forge) (by telepathicgrunt)
Client Tweaks (by BlayTheNinth)
Polymorph (Forge) (by TheIllusiveC4)
NetherPortalFix (by BlayTheNinth)
Macaw's Lights and Lamps (by sketch_macaw)
Macaw's Paintings (by sketch_macaw)
Iceberg (by Grend_G)
AttributeFix (by DarkhaxDev)
Cooking for Blockheads (by BlayTheNinth)
Just Enough Resources (JER) (by way2muchnoise)
Aquaculture 2 (by Shadowclaimer)
Nyf's Quivers (by theNyfaria)
Enchanting Infuser [Forge] (by Fuzs_)
Balm (Forge Edition) (by BlayTheNinth)
Macaw's Fences and Walls (by sketch_macaw)
Puzzles Lib [Forge] (by Fuzs_)
CreativeCore (by CreativeMD)
Just Enough Professions (JEP) (by Mrbysco)
Macaw's Bridges (by sketch_macaw)
Clumps (by Jaredlll08)
Advanced Compass (by dmitrylovin)
Better Advancements (by way2muchnoise)
Corail Tombstone (by Corail_31)
Nature's Compass (by Chaosyr)
Comforts (Forge) (by TheIllusiveC4)
Domum Ornamentum (by OrionOnline)
Wither Skeleton Tweaks (by Shadows_of_Fire)
Fast Leaf Decay (by olafskiii)
Advanced Chimneys (by EnderLanky)
Multi-Piston (by H3lay)
Curios API (Forge) (by TheIllusiveC4)
Chalk (by mortuus_art)
Tetra (by mickelus)
Fabric API (by modmuss50)
FastWorkbench (by Shadows_of_Fire)
ForgeEndertech (by EnderLanky)
Alex's Mobs (by alex_khaan)
Mouse Tweaks (by YaLTeR)
Flywheel (by jozufozu)
Ding (by ohaiiChun)
MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)
Merchant Markers (by Grend_G)
Not Enough Crashes (Forge) (by NatanFudge)
Passthrough Signs (by Girafi)
Macaw's Doors (by sketch_macaw)
Controlling (by Jaredlll08)
Placebo (by Shadows_of_Fire)
AmbientSounds 5 (by 
CreativeMD)

**Comment by Shadows-of-Fire** [comment]
You have two copies of placebo loaded (6.0.3 and 6.0.4)
