### ISSUE TITLE
Placebo-1.18.1-6.1.1 does not work with  Forge 1.18.2

### ISSUE THREAD

**Issue by smmmadden** [Shadows-of-Fire/Placebo#39]
Trying to update my servers and modpacks to 1.18.2 of Forge (build 40.0.12) and it fails and shuts the server down
https://pastebin.com/yPqaBy45

**Comment by RoyalReject** [comment]
Its not intended to work with 1.18.2 I don't see anywhere its marked it should, its build on forge for 1.18.1, you will have to wait for it to get updated, I don't see this as a valid issue but that is just my opinion. Things change internally in forge when Minecraft updates not everything is compatible, and will need updated to the new changes

**Comment by smmmadden** [comment]
understood, just raising the issue to make you aware that it will prevent servers from starting for those upgrading to the latest version of Minecraft.  I use several mods that depend on Placebo, so it is blocking me up from upgrading my servers to 1.18.2.
Thanks,
Steve

**Comment by isaaclepes** [comment]
I came here to check on 1.18.2 status as well. I agree that support for new versions is not a bug, but it would count as a feature request.  I see there was a commit 14 days ago for 1.18.2 support, but the release isn't available anywhere.

**Comment by Shadows-of-Fire** [comment]
6.2.0
