### ISSUE TITLE
Crash w/ Chest in Minecart Recipe

### ISSUE THREAD

**Issue by WenXin20** [Shadows-of-Fire/Placebo#4]
Minecraft v1.12.2
Forge v14.23.5.2838
[NoMoreRecipeConflict](https://www.curseforge.com/minecraft/mc-mods/stimmedcow-nomorerecipeconflict) v0.13
[Better Chesting](https://www.curseforge.com/minecraft/mc-mods/betterchesting) v1.1.1
Placebo v1.6.0

I got this crash after trying to combine a chest with items in it (made possible with Better Chesting) with a minecart in the crafting screen of my player. Vanilla Fix also mentioned that the No More Recipe Conflict Mod was involved. 

[Crash Report](https://paste.dimdev.org/obezosirap.mccrash)

Steps to Reproduce:
1. I had placed the chest in the crafting area first and 
2. Then the output displayed the Tiny Chest from Extra Utilities
3. Then it crashed when I placed the minecart in the crafting area.

**Comment by Shadows-of-Fire** [comment]
This issue isn't actually caused by placebo but I show up in the stacktrace due to my replacement of shapeless recipes.  This is caused by some mod's recipe having a broken Ingredient object.

**Comment by WenXin20** [comment]
Ok, thanks. I suspect it's Metal Transport then.
