### ISSUE TITLE
Placebo disabling? tiered mod

### ISSUE THREAD

**Issue by Winesage** [Shadows-of-Fire/Placebo#41]
Placebo versions after 6.2.0 don't work with tiered mod, disables affixes from tiered and they not only won't show their affixes but also previously tiered items won't give bonuses either.
https://www.curseforge.com/minecraft/mc-mods/tiered-forge

this is the issue page to the tiered mod's github
https://github.com/Stereowalker/tiered/issues/28
it seems they talked to you about it so you should know that it doesn't work but I just wanted to make an issue for it.
Even if you can't post an update for the mod I would appreciate a fix I can do by myself if possible since I'm running a server.
Thank u for your time :)

**Comment by Shadows-of-Fire** [comment]
I'll be honest I have no idea what could even be causing that, but I also don't remember anyone talking to me about it.
It will probably need to be triaged on their end until someone can tell me how it's even possible for me to be breaking it.

**Comment by Shadows-of-Fire** [comment]
Closing in lieu of the other bug, as this is not fixable from my end.
