### ISSUE TITLE
MC 1.16.5 Placebo V. 4.7.0 Non-OPs have command access

### ISSUE THREAD

**Issue by TheMightyMcGrew** [Shadows-of-Fire/Placebo#42]
Non-OP players have access to the command /placebo_serialize, generating json's left and right and changing the conditions for certain blocks which should not be changed.

**Comment by Shadows-of-Fire** [comment]
While a little problematic... That command doesnt allow them to change anything, it just allows for the creation of a json from a game object.

**Comment by TheMightyMcGrew** [comment]
in a modpack like Enigmatic 6, where there are maybe thousands of items entities and everything else they can apply this to, I think it could be a bit more than just a little problematic, seeing as a json is generated for every instance they do this. Even if its not, the report wasnt made to point out something as just  "A little problematic" Non-OPs shouldnt have access to server changing/ file creating powers. My concern is the amount of information involved in someone being an absolute troll and making a file for literally EVERYTHING.

**Comment by Shadows-of-Fire** [comment]
You are aware the command only even works for loot tables, right?

**Comment by TheMightyMcGrew** [comment]
Are you aware of my concern here? Cause it feels like I just made a bug report only for the author of the mod to be completely flippant about it. Yes im aware of what it does, what Im trying to point out is that when a troll player decides to run this for as many instances they can, that generates a lot of files, and while they're only about 470bytes, thats going to add up in larger packs. Im suggesting that maybe server owners shouldnt need to deal with emptying out their placebo_serialized folders everytime someone wants to mess around with commands they shouldnt have access too in the first place!!!
