### ISSUE TITLE
 "Placebo" does not allow me to save datapacks in 1.18.2 - 6.6.0

### ISSUE THREAD

**Issue by 5stigma** [Shadows-of-Fire/Placebo#44]
For some reason "Placebo" does not allow me to save datapacks

Ussing All the Mods 7 Modpack

**Comment by HockeyZman2000** [comment]
having same issue with version 6.6.1, server will not start and says that placebo is erroring. something to do with the enchanting table from apotheosis
[latest.log](https://github.com/Shadows-of-Fire/Placebo/files/9389943/latest.log)

**Comment by Shadows-of-Fire** [comment]
Placebo 6.6.0 is not compatible with apoth 5.4.x, wait for 5.5.0

**Comment by HockeyZman2000** [comment]
Okay thanks for the heads up
