### ISSUE TITLE
PlaceBo server crash

### ISSUE THREAD

**Issue by Proxwian** [Shadows-of-Fire/Placebo#46]
Crash when joining old world on server after update

[crash-2022-08-31_08.50.03-server.txt](https://github.com/Shadows-of-Fire/Placebo/files/9460125/crash-2022-08-31_08.50.03-server.txt)

**Comment by Shadows-of-Fire** [comment]
You need to update Gateways To Eternity, or Placebo, or both.

**Comment by Proxwian** [comment]
You're legend!
