### ISSUE TITLE
(No load DATAPACKS) Error with enter in world - Placebo 6.6.4

### ISSUE THREAD

**Issue by 5stigma** [Shadows-of-Fire/Placebo#47]
(No load DATAPACKS) Error with enter in world

does not provide crashlog, just sends me to Main Menu or Safe Mode.

**Comment by Shadows-of-Fire** [comment]
This likely means you have a mod matched with the wrong version of placebo.  You should update all mods that depend on placebo and attempt again.

**Comment by 5stigma** [comment]
OK, I will try and come back. ty
