### ISSUE TITLE
World crash random

### ISSUE THREAD

**Issue by rylwl** [Shadows-of-Fire/Placebo#48]
I can't comfirm whether the crash reason is placebo or Apotheosis, can you help me?
This is my crash report
[crash report](https://gist.github.com/rylwl/4a8093365ca78f6d0f1730da51b715db)

**Comment by Shadows-of-Fire** [comment]
This has to do with apoth - though this should be impossible unless you added a dimension to the boss spawn list without adding any bosses to that dimension.

Closing since this is the wrong repo.
