### ISSUE TITLE
Game crash after launch.

### ISSUE THREAD

**Issue by bontavi** [Shadows-of-Fire/Placebo#49]
minecraft - 1.19.2
Forge - 43.1.25
Placebo - 6.6.4

I can't start Minecraft with this mod. I have installed Packmenu, but by disabling packmenu I can see that placebo is causing crash.

logs - https://pastebin.com/9Cv1MFN1

**Comment by Shadows-of-Fire** [comment]
I'd like you to actually read the version of placebo you have installed, most importantly the `1.18.2` part.

**Comment by bontavi** [comment]
There is no other version only this one is installed after installing packmenu. Sorry didn't mean to bother you. I just thought I might report. If it is an issue, which can be looked into.

**Comment by Aceplante** [comment]
> There is no other version only this one is installed after installing packmenu. Sorry didn't mean to bother you. I just thought I might report. If it is an issue, which can be looked into.

the issue is you didnt read his reply.
