### ISSUE TITLE
update the mod brack my save

### ISSUE THREAD

**Issue by nightmare3007** [Shadows-of-Fire/Placebo#50]
try to install new mod requsting placebo.
i have old ver and save working ok but [other than placebo] new mod brake the game[no main manu]
i have 6.4.2 for 1.18.2 and when i install 6.6.2 1.18.2 the save will not load [main manu ok but no load save has to load vinala or go back to main manu].
remove [other than placebo] new mod and try again but save will not load [main manu ok but no load save has to load vinala or go back to main manu].
[latest.log](https://github.com/Shadows-of-Fire/Placebo/files/9692130/latest.log)

Log attach

**Comment by Shadows-of-Fire** [comment]
when you update placebo to a new minor version (major.minor.patch) you need to update mods that depend on placebo.
