### ISSUE TITLE
ItemUseEvent doesn't allow for null player

### ISSUE THREAD

**Issue by KaptainWutax** [Shadows-of-Fire/Placebo#53]
The [ItemUseEvent](https://github.com/Shadows-of-Fire/Placebo/blob/7039435c919eed6cdcb190b41c4b433d16c26054/src/main/java/shadows/placebo/events/ItemUseEvent.java#L40) doesn't respect the contract of UseOnContext/ItemUsageContext which marks the player as @ Nullable. Since the hook fires for all use events, it causes compatibility issues for mods that do pass null for the player when creating fake usage contexts. We ran into this problem with the [ispawner](https://github.com/Iskallia/iSpawner/blob/fbb84ce2ba0375533031a028c55d6bb118faeab4/common/src/main/java/iskallia/ispawner/world/spawner/SpawnerUsageContext.java#L17) mod.

**Comment by Shadows-of-Fire** [comment]
This can probably be addressed for 1.19.2+ but older versions are out of development.  You'd probably be best to simply use a fake player, as it seems you might be the only people in existence passing a null player to the context object.
