### ISSUE TITLE
Client freeze and server crash

### ISSUE THREAD

**Issue by abhemanyus** [Shadows-of-Fire/Placebo#54]
Whenever I visit a particular point on the map, which is basically in the middle of nowhere (-20920,120,25 in the Nether), my client freezes and the server I was playing on crashes.
Here's the crash log https://mclo.gs/ljukmVz
The location contains a nether portal, and train tracks and station from Create.

**Comment by Shadows-of-Fire** [comment]
Whatever issue you are having is unrelated to placebo.  The error placebo prints out is a caught connection error and is not propagating beyond that log message.
