### ISSUE TITLE
Helmet "+total attack damage" is not effective

### ISSUE THREAD

**Issue by rtxyd** [Shadows-of-Fire/Placebo#57]
in 1.19.2, test with dummmy, jei, and apotheosis, this affix seems not implement.

**Comment by Shadows-of-Fire** [comment]
wrong repo

**Comment by rtxyd** [comment]
@Shadows-of-Fire What format should I use, mc version, mod version, lib version? If you told me, I would repost this issue.

**Comment by rtxyd** [comment]
My bad, sorry.
