### ISSUE TITLE
[1.19.2] Crash with Placebo 7.1.6 and Apotheosis 6.1.2

### ISSUE THREAD

**Issue by Mitchell5200** [Shadows-of-Fire/Placebo#58]
Full game crash with Placebo 7.1.6 and Apotheosis 6.1.2 during world load or shortly after, does not occur with 7.1.5.
Something that might be related, once i loaded the world with 7.1.5 an apoth mini boss spawned.
https://mclo.gs/Y9AwKEY
tested in ATM8 1.0.14 (alpha dev export)

**Comment by Shadows-of-Fire** [comment]
7.1.6 corresponds with 6.1.3, you'll have to update both

**Comment by Mitchell5200** [comment]
Ah, my bad, that file had not shown up in CF for me yet, found it now, ty

**Comment by Shadows-of-Fire** [comment]
Apoth files take a bit more pending time than placebo (probably due to file size and automated scans)
You just happened to update too quickly :p
