### ISSUE TITLE
[1.14.4] Server crash - sidedness issue- NoSuchMethodError: shadows.placebo.util.SpawnerBuilder.build(Lnet/minecraft/worl

### ISSUE THREAD

**Issue by ProsperCraft** [Shadows-of-Fire/Placebo#6]
https://gist.github.com/ProsperCraft/f755d7dd798399f3cef40289dd359c33

	Placebo-1.14.4-2.1.7.jar
forge-1.14.4-28.0.45

**Comment by Shadows-of-Fire** [comment]
More of a version mismatch, will be fixed by apotheosis 2.1
