### ISSUE TITLE
forge 1.12 crash

### ISSUE THREAD

**Issue by Aceplante** [Shadows-of-Fire/Placebo#60]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: placebo Failed load class: shadows.placebo.Placebo

**Comment by Shadows-of-Fire** [comment]
1.12 is not supported

**Comment by Aceplante** [comment]
nevermind it seems to be caused my some other incompatibility anyways
