### ISSUE TITLE
[1.18.2] Server crash with Etched mod

### ISSUE THREAD

**Issue by LeanDot5996** [Shadows-of-Fire/Placebo#61]
When I am trying to use jukebox with hopper feature from the Etched mod the server crashes, I have tried it without Placebo and everything works fine.

**Crash Report:**
[crash-2023-06-08_19.42.29-server.txt](https://github.com/Shadows-of-Fire/Placebo/files/11696890/crash-2023-06-08_19.42.29-server.txt)

**Comment by Shadows-of-Fire** [comment]
Duplicate of https://github.com/Shadows-of-Fire/Placebo/issues/53

It _probably_ won't be fixed as 18.2 is out of dev, you could ask the other mod to pass in a fakeplayer instead of null, which would resolve the crash.

**Comment by Shadows-of-Fire** [comment]
Closing as not planned, 1.18 will not be receiving updates.
