### ISSUE TITLE
Crash on Pre-launch, dependency issue

### ISSUE THREAD

**Issue by Sixdd6** [Shadows-of-Fire/Placebo#68]
Forge: 43.2.0
Placebo: 1.19.2-7.3.3
Apotheosis: 1.19.2-6.4.0

Game crashes on startup complaining that I don't have the right version of Placebo.
[debug.log](https://github.com/Shadows-of-Fire/Placebo/files/12697143/debug.log)

**Comment by Sixdd6** [comment]
Followup: noticed that the forge version was outdated as well and updated to 43.3.0. Same result.

**Comment by Shadows-of-Fire** [comment]
If I'm reading the log correctly its saying the Placebo jar you have is actually an Apotheosis jar.
I have no idea how that could've happened, but I can verify that the jar on CF is correct, so try reinstalling Placebo, I guess.

**Comment by Sixdd6** [comment]
Not sure how it happened but I redownloaded and everything is peachy, gremlins in the machine I guess.
