### ISSUE TITLE
Crash on pressing NUMPAD 8

### ISSUE THREAD

**Issue by Auuki** [Shadows-of-Fire/Placebo#69]
Placebo 7.3.3 crashes when I try to type a seed including an 8 (used NUMPAD). Based on the commits I assume 9 will also crash. Going back to the previous version solves the issue.
EDIT Confirmed it's just NUMPAD 8/9 keys pressed at any point in the game. They are bound to patreon trails.
[debug.log](https://github.com/Shadows-of-Fire/Placebo/files/12716024/debug.log)

**Comment by Saereth** [comment]
confirming as well, reported by Matrixis while playing ftb genesis but num pad 9 for him
https://gist.github.com/Saereth/be3192ba61c2100830a009379b3eaeb9

**Comment by TwistedAkai** [comment]
Numpad 9, but same bug https://mclo.gs/oAXgHVB
Encountered while playing ATM8. Issue follows patreon bindings and occurs in menu or while typing connection info. Does not occur once connected to world.
