### ISSUE TITLE
Render thread/ERROR

### ISSUE THREAD

**Issue by Krimatoria** [Shadows-of-Fire/Placebo#77]
Placebo-1.19.2-7.3.5.jar

[08Feb2024 02:54:02.308] [Render thread/ERROR] [placebo/]: Codec failure for type Affix Loot Entry, message: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:crude_scythe

**Comment by Shadows-of-Fire** [comment]
That is user error for providing an invalid item.

**Comment by Krimatoria** [comment]
> Это ошибка пользователя, связанная с предоставлением недопустимого элемента.

Do you need to do something about it?

**Comment by SiverDX** [comment]
> > Это ошибка пользователя, связанная с предоставлением недопустимого элемента.
> 
> Do you need to do something about it?

they can't
install malum or remove the datapack part which adds this
