### ISSUE TITLE
i have no idea why this keeps happening

### ISSUE THREAD

**Issue by zombiegunner262** [Shadows-of-Fire/Placebo#8]
https://mclo.gs/RHXXTqz if you could help me that would be nice
the version of your mod is Placebo-1.12.2-1.6.0.jar and the version of minecraft is 1.12.2

**Comment by Shadows-of-Fire** [comment]
Because forge thought it was a good feature.  Not a bug, nor does it have any impact on anything.

**Comment by zombiegunner262** [comment]
thank you do you know why the server is crashing then

**Comment by Shadows-of-Fire** [comment]
theres no crash in that log
