### ISSUE TITLE
Unable to Start Apotheosis/Placebo

### ISSUE THREAD

**Issue by Reyzerbit** [Shadows-of-Fire/Placebo#80]
Forge 1.20.1 (Tested on both 47.2.17 and 47.2.21)
Placebo v8.6.1
Apotheosis v7.3.3

I removed all other mods from my modpack other than just Apotheosis and Placebo, and I get the following error (it doesn't appear in debug or latest.log, only when I use the game output window)
`Caused by: java.lang.RuntimeException: java.lang.IncompatibleClassChangeError: class dev.shadowsoffire.placebo.color.GradientColor cannot inherit from final class net.minecraft.network.chat.TextColor`

Here's my [debug.log](https://github.com/Shadows-of-Fire/Placebo/files/14675585/debug.log) and my [latest.log](https://github.com/Shadows-of-Fire/Placebo/files/14675586/latest.log)

Edit: Confirmed this occurs also with Placebo 8.6.0 and 8.5.9

**Comment by Shadows-of-Fire** [comment]
This (annoyingly) happens when Access Transformers fail to apply, which happens when there is a dependency error.  It should be near the top of your log file.

If you have just those two mods you would be missing the required dependency Apothic Attributes.

**Comment by Reyzerbit** [comment]
ah thank you much! that did it

**Comment by Darkmega18** [comment]
ah. good to know.
