### ISSUE TITLE
[1.16.5] 4.7.1 client can still launch on a 4.7.0 server, but it causes significant lag

### ISSUE THREAD

**Issue by NighthowlerStudios** [Shadows-of-Fire/Placebo#82]
I assume there is a discrepancy between the expected packet order and data between the two versions, assumedly because of the supporter wings backport.  It would lead to packet corruption that causes significant lag that gets worse the longer the player is in the world.

It was a very strange issue and hard to track.  The server itself was lagging as it spammed "can't keep up!".  all I had to do was hop around my world between dungeons until it became unplayable.

If both server and client are on 4.7.1, this issue disappears.

worst case scenario, sitting in a heavy dungeon that does not cause performance issues normally, caused constant tick spikes of 5 seconds per tick.

EVEN IF this is incorrect information, please change the json of Placebo so that it won't load if client and server are out of sync on versions :)  this issue is a security risk that could bring down any server using 4.7.

You can reproduce this yourself using Kaleidio's Battle Pack 5.6.3, and forcing Placebo to be an older version on the server.

**Comment by Kaleidio** [comment]
This issue is due to Line #75 in WingsManager.java.  That Client event is gonna send a packet regardless if the server can decode it safely or not.

**Comment by NighthowlerStudios** [comment]
Apologies for the bad report. Turned out to be some totally different issue I thought disappeared when it didn't.
