### ISSUE TITLE
[1.19.2] Crashing on startup

### ISSUE THREAD

**Issue by SakaiIchiiro** [Shadows-of-Fire/Placebo#83]
Hey! I've searched the previous solved issues on both apotheosis and placebo to find this error I'm having on startup and I found it - the exact same error:

`Caused by: java.lang.RuntimeException: java.lang.IncompatibleClassChangeError: class dev.shadowsoffire.placebo.color.GradientColor cannot inherit from final class net.minecraft.network.chat.TextColor`

The thing is, this error appeared for someone in 1.20.1, who was missing the Apothic Attributes mod. I looked into it and I've seen that in 1.19.2 this feature of the mod was supposed to be present in the main Apotheosis file. Do you have any idea what could it be?

My versions are Placebo 7.4.0 and Apotheosis 6.5.1.

**Comment by Shadows-of-Fire** [comment]
This happens if you have _any_ dependency error in your setup since forge will not wpply AccessTransformers if a dependency error occurs.

You can figure out the error by reading your game log
