### ISSUE TITLE
Crash when opening inventory on server while in creative

### ISSUE THREAD

**Issue by UnknownVariables-here** [Shadows-of-Fire/Placebo#84]
Only happens on a multiplayer server in creative
Using placebo / apotheosis 1.20.1
ran this test on a fresh instance / server build with only those mods
https://mclo.gs/wWXHxKh

**Comment by Shadows-of-Fire** [comment]
Your Apotheosis main module config `apotheosis.cfg` is mismatched between the client and server.  This file must match exactly, since it is read on startup.
