### ISSUE TITLE
[1.21] [Neoforge] Crash with Xaero's World Map after 21.0.76

### ISSUE THREAD

**Issue by ffuentesm** [Shadows-of-Fire/Placebo#86]
I want to know which mod is responsible for the crash.  If I launch either of them alone it works, but if I launch it both together it crashes.

XaerosWorldMap_1.38.8_NeoForge_1.21.jar
Neoforge: 21.0.76
Placebo-1.21-9.3.3.jar

New Neoforge update changes cause a crash on launch. I think is the new client event hooks

Log: [https://pastebin.com/5AjkH3s1](https://legacy.curseforge.com/linkout?remoteUrl=https%253a%252f%252fpastebin.com%252f5AjkH3s1)
java.lang.NullPointerException: Cannot invoke "xaero.map.graphics.GLObjectDeleter.work()" because "xaero.map.WorldMap.glObjectDeleter" is null

**Comment by Shadows-of-Fire** [comment]
Placebo, as an experiment, starts up the forge `GAME` event bus earlier than usual.  This experiment is being done to see how this change would impact mods if this change was made in NeoForge directly.  Ideally, Xaeros would add a null check here against the value of `glObjectDeleter`

**Comment by VictoriaSilver** [comment]
Seems to be fixed as of [World Map 1.39.0](https://chocolateminecraft.com/update.php?mod_id=2).
