### ISSUE TITLE
Mod Conflict with XPlus Autofish. Works without Placebo, Fails with Placebo enabled [MC 1.21.1 Neoforge 21.1.21+]

### ISSUE THREAD

**Issue by Slaymeister** [Shadows-of-Fire/Placebo#89]
Mod conflict with XPlus Autofish. Error occurs during launch. XPlus works without Placebo and fails with it enabled.

Minecraft 1.21.1
Neoforge 21.1.21+ (tested with 21.1.21 and 21.1.23 with same results)

Full Mod List:
XPlus Autofish 1.3.1 https://www.curseforge.com/minecraft/mc-mods/x-autofish
Cloth 15.0.130 https://www.curseforge.com/minecraft/mc-mods/cloth-config
Placebo-1.21.1-9.4.1 https://www.curseforge.com/minecraft/mc-mods/placebo

Error:
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "com.wudji.xplusautofish.XPlusAutofish.tick(net.minecraft.client.Minecraft)" because "this.autofish" is null

Crash Report:
https://pastebin.com/S1PrLJ5A

Repro:
In Curseforge, install a new instance of Minecraft 1.21 with Neoforge 21.1.21+. Add XPlus Autofish, Cloth API, and Placebo. Launch instance.  Crash will occur before main menu.

**Comment by Slaymeister** [comment]
https://github.com/Wudji/XPlus-AutoFish/issues/22

**Comment by Shadows-of-Fire** [comment]
That's a cheat mod, I don't have any interest in fixing compat with it.

**Comment by Slaymeister** [comment]
Thank you for looking into it.

**Comment by Slaymeister** [comment]
Your comment keeps coming back on me and I hope you'll entertain a quick question about it. I believe you have the prerogative to work on whatever interests you, so I'm not trying to argue with you about working on compatibility. It is just your classification of the mod as a "cheat" that confuses me.

I quite enjoy your mods and use them in many playthroughs as an essential part of some of my favorite packs, so I am familiar with their mechanics. Many of your mods focus on AFK or simplified mob harvesting, such as Apotheosis spawners, and even unattended drop farming such as with Hostile Neural Networks. I have used HNN in the ATM packs to automate the gathering of literally millions of drops, as manufacturing ATM Stars in that pack require millions of diamonds, emerald, nether stars, etc. 

My question is can you help me understand the difference between a mod that automates resource gathering and a cheat mod? The fishing mod in question allows you to AFK the as boring as watching paint dry fishing mechanic and nothing more. Can you help me understand why AFKing a vanilla grind is a cheat but unattended drop gathering is not? 

As I said, I support your right to work on what interests you, so this question is just out of curiosity.

**Comment by meeprdib** [comment]
I'm assuming it's because the mod (by the looks of it) is entirely client-side, and could be abused on servers and whatnot.

**Comment by meeprdib** [comment]
Considering you're playing modded Minecraft, why don't you use a mod that fleshes out fishing automation in interesting ways instead of using a mod that makes it so you have to AFK overnight to get items? I could only imagine using that mod on a vanilla server to get fishing loot easier, not in an actual "modded" setting, if that makes sense.

**Comment by Slaymeister** [comment]
It is entirely client side, but I can think of other mods that can be client side only that are fundamental to a good client, such as JEI. If you consider the way vanilla unlocks recipes to be important, JEI is a cheat mod. 

I have also looked at more content oriented fishing mods. They add things like nets or "fish farm" blocks that output fish loot to a nearby container, but all of them incorporate their own loot tables making their out-of-the-box mod integration sketchy. For example, I am using Aquaculture 2 as part of the All The Mods 10 pack that is the foundation of my Minecraft instance. It adds a ton of new content, which is interesting, but it adds no automation instead preferring to create more reasons to play the fishing minigame. I recently needed some of the neptunium ingots Aquaculture 2 adds to the game as part of an ATM integrated recipe, and the RNG was unkind. It took a couple hours of the fishing mini game to get what I needed, which inspired me to put down Minecraft and go play something else for a couple days. None of the fishing automation mods that I have seen would have allowed me to build a solution for this because of the built-in loot tables - you either sit there and watch the bobber or go do something else. 

So I think your points are good to bring up, mostly because they illustrate why none of the content oriented, non-client side solutions solve fishing automation in modded minecraft. The only automation solution for fishing that I've seen that plays well with content mods is to automate the vanilla mechanic, and that means a client mod. Incidentally, if you know of an exception to this, I'm very interested in hearing about it.

**Comment by Wudji** [comment]
See Placebo https://github.com/Shadows-of-Fire/Placebo/issues/86.
Xaero's map allows players to get much more information about the surroundings than other players, which can run entirely on client side. If that's the case, Xaero's map is a cheat mod.

**Comment by Shadows-of-Fire** [comment]
A great many servers _do_ consider certain features of Xaero's (such as player radar) to be cheats.  Anyway, this discussion is not relevant to Placebo, so I'll be locking this.
