### ISSUE TITLE
[1.21.1] JSON brewing mixes not working on dedicated servers

### ISSUE THREAD

**Issue by kang3209** [Shadows-of-Fire/Placebo#95]
The potion recipe is not working.
It works locally, but does not work on servers with the same mode applied.

https://github.com/user-attachments/assets/298552b8-0542-41df-b0cd-6b35d597f5b8

This is a video that's trying to create a potion of resistance.

This is a list of modes applied to the server

ApothicAttributes-1.21.1-2.3.0.jar
appleskin-neoforge-mc1.21-3.0.5.jar
architectury-13.0.6-neoforge.jar
artifacts-neoforge-12.0.5.jar
AxesAreWeapons-1.9.2-neoforge-1.21.jar
balm-neoforge-1.21.1-21.0.19.jar
caelus-neoforge-7.0.1+1.21.1.jar
cloth-config-15.0.130-neoforge.jar
connectedglass-1.1.12-neoforge-mc1.21.jar
connector-2.0.0-beta.2+1.21.1-full.jar
corpse-neoforge-1.21.1-1.0.14.jar
cosmeticarmorreworked-1.21.1-v1-neoforge.jar
craftingtweaks-neoforge-1.21.1-21.1.2.jar
CraftTweaker-neoforge-1.21-20.0.22.jar
curios-neoforge-9.0.9+1.21.jar
DungeonCrawl-NeoForge-1.21-2.3.14.jar
DungeonsArise-1.21.x-2.1.60-release.jar
DungeonsAriseSevenSeas-1.21.x-1.0.3.2-neoforge.jar
EasyMagic-v21.0.4-1.21-NeoForge.jar
elytraslot-neoforge-9.0.0+1.21.jar
endersdelight-1.21-1.0.1.jar
FarmersDelight-1.21-1.2.4.jar
forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar
fusion-1.1.1a-neoforge-mc1.21.jar
GatewaysToEternity-1.21.1-5.0.0.jar
inventoryhud.neoforged.1.21.1-3.4.26.jar
Jade-1.21.1-NeoForge-15.3.4.jar
jei-1.21.1-neoforge-19.18.3.204.jar
journeymap-neoforge-1.21-6.0.0-beta.25.jar
journeymap-webmap-neoforge-1.21-1.0.1.jar
Neat-1.21-36-NEOFORGE.jar
Neruina-2.1.2-neoforge+1.21.jar
oceansdelight-neoforge-1.0.3-1.21.jar
open-parties-and-claims-neoforge-1.21-0.23.2.jar
Placebo-1.21.1-9.5.2.jar
PuzzlesLib-v21.1.3-1.21.1-NeoForge.jar
sophisticatedbackpacks-1.21-3.20.9.1060.jar
sophisticatedcore-1.21-0.6.31.631.jar
sophisticatedstorage-1.21-0.10.26.816.jar
Stackable   Potions-forge-1.21-1.0.0.jar
supermartijn642corelib-1.1.17i-neoforge-mc1.21.jar
trimmable_tools-neoforge-1.21-2.0.2.jar
twilightforest-1.21.1-4.6.2780-universal.jar
veinmining-neoforge-5.0.0-beta.2+1.21.jar
waystones-neoforge-1.21.1-21.1.3.jar

**Comment by Shadows-of-Fire** [comment]
This ended up being due to a problem with how the brewing mixes were applied during the first data reload on a dedicated server. Since the reload happens before the server is statically accessible, they were never getting applied.  I've resolved to just applying them manually on server start, which fixes the issue.

**Comment by kang3209** [comment]
> This ended up being due to a problem with how the brewing mixes were applied during the first data reload on a dedicated server. Since the reload happens before the server is statically accessible, they were never getting applied. I've resolved to just applying them manually on server start, which fixes the issue.

"I've resolved to just applying them manually on server start, which fixes the issue."

How can I do that? I don't know how.
I'd appreciate it if you could tell me

**Comment by Shadows-of-Fire** [comment]
Update to Placebo 9.5.3

**Comment by kang3209** [comment]
thank you so much!!!
