### ISSUE TITLE
server kicks the player when joining, seems to be placebo?

### ISSUE THREAD

**Issue by VaporeonScripts** [Shadows-of-Fire/Placebo#96]
https://mclo.gs/jzNKX5O
neoforge 1.21.1 .72

**Comment by Shadows-of-Fire** [comment]
What makes you think this is related to placebo?

**Comment by VaporeonScripts** [comment]
it says placebo at the end of code error, idk if its really related

**Comment by meeprdib** [comment]
Don't see any fatal issues related to Placebo, the player is being kicked because they're sending too many packets.
```
[26ott2024 21:13:31.596] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: NatsuyamiOnArch lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Packet too large: size 3107931 is over 8
--
8743 | [26ott2024 21:13:31.597] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: NatsuyamiOnArch left the game
```
Try installing a mod like [Packet Fixer](https://www.curseforge.com/minecraft/mc-mods/packet-fixer) to help with that kind of issue.

**Comment by VaporeonScripts** [comment]
im already using that

**Comment by VaporeonScripts** [comment]
wait, it disappeared lmao

**Comment by meeprdib** [comment]
Make sure it's installed on both client and server.

**Comment by VaporeonScripts** [comment]
yeah, i might have deleted it for error when deleting client mods from the server

**Comment by VaporeonScripts** [comment]
just started again the server, gonna see if it works
